package org.gxz.znrl.mapper;

import org.gxz.znrl.entity.OrganizationRole;
import org.gxz.znrl.entity.OrganizationRoleCriteria;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrganizationRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    int countByExample(OrganizationRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    int deleteByExample(OrganizationRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    int insert(OrganizationRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    int insertSelective(OrganizationRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    List<OrganizationRole> selectByExample(OrganizationRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    OrganizationRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrganizationRole record, @Param("example") OrganizationRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrganizationRole record, @Param("example") OrganizationRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrganizationRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrganizationRole record);
}